PARAMATERS = sorted([
    # Fuel parameters
    'combustion',       # Boolean; combustion engine
    'weight reduction', # Decrease in mass (kg)
    'Benzene',
    'auxiliary power demand',   # Power demand for heating, cooling, and auxiliaries (kW)
    # Emissions to air
    'CH4',              # Methane
    'CO',               # Carbon monoxide
    'N2O',              # Dinitrogen monoxide
    'NH3',              # Ammonia
    'NMVOC',            # Non-methane volatile organics
    'NO2',              # Nitrogen dioxide
    'NOx',              # Nitrogen oxides (other than NO2)
    'PM',               # Particulate matter < 10 m
    'CNG mass',
    'CNG tank mass intercept',
    'CNG tank mass slope',
    'CO2 per kg fuel',
    'H2 mass',
    'H2 tank mass per energy',
    'HC',
    'SO2 per kg fuel',
    'aerodynamic drag coefficient',
    'auxilliary power base demand',
    'average passenger mass',
    'average passengers',
    'battery DoD',
    'battery cell energy density',
    'battery cell mass share',
    'battery cell power density',
    'battery cell production energy',
    'battery cell production energy electricity share',
    'battery charge efficiency',
    'battery discharge efficiency',
    'battery lifetime kilometers',
    'battery onboard charging infrastructure cost',
    'cargo mass',
    'charger mass',
    'combustion exhaust treatment cost',
    'combustion power share',
    'combustion powertrain cost per kW',
    'converter mass',
    'cooling energy consumption',
    'cooling thermal demand',
    'diesel mass',
    'drivetrain efficiency',
    'electric powertrain cost per kW',
    'emotor fixed mass',
    'emotor mass per power',
    'energy battery mass',
    'energy cost per kWh',
    'energy storage battery cost per kWh',
    'engine efficiency',
    'engine fixed mass',
    'engine mass per power',
    'frontal area',
    'fuel cell ancillary BoP mass per power',
    'fuel cell cost per kW',
    'fuel cell essential BoP mass per power',
    'fuel cell lifetime kilometers',
    'fuel cell own consumption',
    'fuel cell power area density',
    'fuel cell power share',
    'fuel cell stack efficiency',
    'fuel tank cost per kg',
    'fuel tank mass per energy',
    'glider base mass',
    'glider cost intercept',
    'glider cost slope',
    'glider lightweighting cost per kg',
    'heat pump cost',
    'heating energy consumption',
    'heating thermal demand',
    'interest rate',
    'inverter mass',
    'kilometers per year',
    'lifetime kilometers',
    'lightweighting',
    'maintenance cost per glider cost',
    'markup factor',
    'petrol mass',
    'power battery cost per kW',
    'power distribution unit mass',
    'power to mass ratio',
    'powertrain fixed mass',
    'powertrain mass per power',
    'rolling resistance coefficient',
])
